# Generated by Django 2.2.4 on 2020-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_type', models.IntegerField()),
                ('recommend_id', models.CharField(max_length=50, verbose_name='推荐id')),
                ('recommend_text', models.CharField(max_length=200, verbose_name='推荐语')),
                ('recommend_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-recommend_time'],
            },
        ),
    ]
