# Generated by Django 2.2.4 on 2020-05-16 08:33

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anthology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthology_title', models.CharField(default='默认文选', max_length=20)),
                ('anthology_cover', models.ImageField(default='covers/anthology.jpg', upload_to='covers/')),
                ('anthology_describe', models.CharField(default='暂无描述', max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50)),
                ('category', models.CharField(default='数据分析', max_length=20)),
                ('serial', models.IntegerField(default='1')),
                ('author_copy', models.CharField(blank=True, max_length=20)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('article_cover', models.ImageField(upload_to='covers/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('read_num', models.IntegerField(default='0')),
                ('reader_num', models.IntegerField(default='0')),
                ('like_num', models.IntegerField(default='0')),
                ('collect_num', models.IntegerField(default='0')),
                ('comment_num', models.IntegerField(default='0')),
                ('is_active', models.BooleanField(default=True)),
                ('is_pay', models.BooleanField(default=False)),
                ('need_pay', models.IntegerField(default='0')),
                ('anthology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Anthology')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ReaderNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('once_read_time', models.DateTimeField(auto_now_add=True)),
                ('more_read_time', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
