# Generated by Django 2.2.4 on 2020-05-16 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=11)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('sex', models.CharField(blank=True, max_length=5)),
                ('portrait', models.ImageField(blank=True, default='/img/userhead.jpg', upload_to='heads/')),
                ('city', models.CharField(blank=True, max_length=20)),
                ('autograph', models.CharField(blank=True, default='这个人很懒，什么也没有写', max_length=100)),
                ('id_card', models.CharField(blank=True, max_length=18)),
                ('exp', models.IntegerField(default='0')),
                ('rank', models.IntegerField(default='0')),
                ('coin', models.IntegerField(default='0')),
                ('level', models.CharField(default='无', max_length=10)),
                ('badge', models.ImageField(blank=True, upload_to='badges/')),
                ('money', models.IntegerField(default='0')),
                ('is_vip', models.BooleanField(default=False)),
                ('vip_rank', models.IntegerField(default='0')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
